services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: http://localhost:3000,https://thomasavice.com 